experiment:
  name: "treesegmentation"
  n_epochs: 100
  batch_size: 4
  device: "cuda"
  torch_seed: 7
  numpy_seed: 7
  version: 0
  n_workers: 4
  eval_metrics: "Accuracy/Recall/Dice"
  eval_metrics_genus: "Dice"
  eval_metrics_family: "Dice"
  selection_metric: "Dice"

dataset:
  name: "pastis"
  w_size: 768
  h_size: 768
  final_size: 768
  shuffle: True
  task: "Segmentation"
  data_mode: "SITS"
  n_classes: 20
  dataset_path: "/home/mila/v/venkatesh.ramesh/scratch/pastis_dataset/PASTIS"
  ref_date: "2018-09-01"
  mono_date: None
  n_classes_genus: 12
  n_classes_family: 5
  time_dim: null
  cv: "3"

model:
  name: "fpn"
  loss: "CrossEntropy"
  lr: 0.001
  lr_step: 1000
  optim: "Adam"

log_steps:
  loss: 50
  val: 300
  visualization: 100
  checkpoint: 500

base_exp: "pastis_experiment_fpn"
comments: "DiceLoss+weights on the pastis."

wandb:
  tags: ["fpn", "CrossEntropy", "20_classes", "semseg", "pastis"]
